[package]
name = "GameBoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb_core = {path="./gb_core"}

[dependencies.sdl2]
version = "^0.35.2"
default-features = true
features = ["ttf"]